// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Test1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
lv_obj_t * ui_Main;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Hour;
lv_obj_t * ui_Colon;
lv_obj_t * ui_Minute;


// SCREEN: ui_SelectionMenu
void ui_SelectionMenu_screen_init(void);
void ui_event_SelectionMenu(lv_event_t * e);
lv_obj_t * ui_SelectionMenu;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
void ui_event_Label5(lv_event_t * e);
lv_obj_t * ui_Label5;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label10;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label4;


// SCREEN: ui_WIFIINFO
void ui_WIFIINFO_screen_init(void);
void ui_event_WIFIINFO(lv_event_t * e);
lv_obj_t * ui_WIFIINFO;
lv_obj_t * ui_Label8;


// SCREEN: ui_Environment
void ui_Environment_screen_init(void);
void ui_event_Environment(lv_event_t * e);
lv_obj_t * ui_Environment;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_HourWeather;
lv_obj_t * ui_HourWeather11;
lv_obj_t * ui_Image2;
lv_obj_t * ui_WTime1;
lv_obj_t * ui_WTemp1;
lv_obj_t * ui_HourWeather1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_WTime2;
lv_obj_t * ui_WTemp2;
lv_obj_t * ui_HourWeather2;
lv_obj_t * ui_Image4;
lv_obj_t * ui_WTime3;
lv_obj_t * ui_WTemp3;
lv_obj_t * ui_HourWeather3;
lv_obj_t * ui_Image5;
lv_obj_t * ui_WTime4;
lv_obj_t * ui_WTemp4;
lv_obj_t * ui_HourWeather4;
lv_obj_t * ui_Image6;
lv_obj_t * ui_WTime5;
lv_obj_t * ui_WTemp5;
lv_obj_t * ui_HourWeather5;
lv_obj_t * ui_Image7;
lv_obj_t * ui_WTime6;
lv_obj_t * ui_WTemp6;
lv_obj_t * ui_HourWeather6;
lv_obj_t * ui_Image8;
lv_obj_t * ui_WTime7;
lv_obj_t * ui_WTemp7;
lv_obj_t * ui_HourWeather7;
lv_obj_t * ui_Image9;
lv_obj_t * ui_WTime8;
lv_obj_t * ui_WTemp8;
lv_obj_t * ui_HourWeather8;
lv_obj_t * ui_Image10;
lv_obj_t * ui_WTime9;
lv_obj_t * ui_WTemp9;
lv_obj_t * ui_HourWeather9;
lv_obj_t * ui_Image11;
lv_obj_t * ui_WTime10;
lv_obj_t * ui_WTemp10;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel4;
void ui_event_AQIBar(lv_event_t * e);
lv_obj_t * ui_AQIBar;
lv_obj_t * ui_AQIVal;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel1;
void ui_event_TempBar(lv_event_t * e);
lv_obj_t * ui_TempBar;
lv_obj_t * ui_TEMP;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel3;
void ui_event_HumidBar(lv_event_t * e);
lv_obj_t * ui_HumidBar;
lv_obj_t * ui_Humid;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel5;
void ui_event_COBar(lv_event_t * e);
lv_obj_t * ui_COBar;
lv_obj_t * ui_CO2;
lv_obj_t * ui_Label12;


// SCREEN: ui_timeChange
void ui_timeChange_screen_init(void);
void ui_event_timeChange(lv_event_t * e);
lv_obj_t * ui_timeChange;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
void ui_event_Slider3(lv_event_t * e);
lv_obj_t * ui_Slider3;
lv_obj_t * ui_Hour1;
lv_obj_t * ui_Minute1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SelectionMenu, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_SelectionMenu_screen_init);
    }
}
void ui_event_SelectionMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_Main_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WIFIINFO, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_WIFIINFO_screen_init);
    }
}
void ui_event_Label5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WIFIINFO, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_WIFIINFO_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Environment, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_Environment_screen_init);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_timeChange, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_timeChange_screen_init);
    }
}
void ui_event_WIFIINFO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SelectionMenu, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_SelectionMenu_screen_init);
    }
}
void ui_event_Environment(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SelectionMenu, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_SelectionMenu_screen_init);
    }
}
void ui_event_AQIBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_AQIVal, target, "", "");
    }
}
void ui_event_TempBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_TEMP, target, "", " F");
    }
}
void ui_event_HumidBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Humid, target, "", "%");
    }
}
void ui_event_COBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_CO2, target, "", "ppm");
    }
}
void ui_event_timeChange(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SelectionMenu, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_SelectionMenu_screen_init);
    }
}
void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Hour, target, "", "");
        _ui_slider_set_text_value(ui_Hour1, target, "", "");
    }
}
void ui_event_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Minute, target, "", "");
        _ui_slider_set_text_value(ui_Minute1, target, "", "");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_SelectionMenu_screen_init();
    ui_WIFIINFO_screen_init();
    ui_Environment_screen_init();
    ui_timeChange_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
