// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Test1

#include "../ui.h"

void ui_Environment_screen_init(void)
{
    ui_Environment = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Environment, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Environment, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Environment, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Environment);
    lv_obj_set_width(ui_Panel2, 480);
    lv_obj_set_height(ui_Panel2, 206);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -1);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourWeather = ui_HourWeather_create(ui_Panel2);
    lv_obj_set_x(ui_HourWeather, 0);
    lv_obj_set_y(ui_HourWeather, 0);



    ui_HourWeather11 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_HourWeather11, 75);
    lv_obj_set_height(ui_HourWeather11, 175);
    lv_obj_set_x(ui_HourWeather11, -41);
    lv_obj_set_y(ui_HourWeather11, 72);
    lv_obj_set_align(ui_HourWeather11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HourWeather11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourWeather11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourWeather11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_HourWeather11);
    lv_img_set_src(ui_Image2, &ui_img_sunny_png);
    lv_obj_set_width(ui_Image2, 129);
    lv_obj_set_height(ui_Image2, 121);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 150);

    ui_WTime1 = lv_label_create(ui_HourWeather11);
    lv_obj_set_width(ui_WTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTime1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WTime1, "1300");
    lv_obj_set_style_text_color(ui_WTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTime1, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WTemp1 = lv_label_create(ui_HourWeather11);
    lv_obj_set_width(ui_WTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTemp1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WTemp1, "45");
    lv_obj_set_style_text_color(ui_WTemp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTemp1, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourWeather1 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_HourWeather1, 75);
    lv_obj_set_height(ui_HourWeather1, 175);
    lv_obj_set_x(ui_HourWeather1, -41);
    lv_obj_set_y(ui_HourWeather1, 72);
    lv_obj_set_align(ui_HourWeather1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HourWeather1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourWeather1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourWeather1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_HourWeather1);
    lv_img_set_src(ui_Image3, &ui_img_sunny_png);
    lv_obj_set_width(ui_Image3, 129);
    lv_obj_set_height(ui_Image3, 121);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 150);

    ui_WTime2 = lv_label_create(ui_HourWeather1);
    lv_obj_set_width(ui_WTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTime2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WTime2, "1400");
    lv_obj_set_style_text_color(ui_WTime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTime2, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WTemp2 = lv_label_create(ui_HourWeather1);
    lv_obj_set_width(ui_WTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTemp2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WTemp2, "47");
    lv_obj_set_style_text_color(ui_WTemp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTemp2, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourWeather2 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_HourWeather2, 75);
    lv_obj_set_height(ui_HourWeather2, 175);
    lv_obj_set_x(ui_HourWeather2, -41);
    lv_obj_set_y(ui_HourWeather2, 72);
    lv_obj_set_align(ui_HourWeather2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HourWeather2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourWeather2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourWeather2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_HourWeather2);
    lv_img_set_src(ui_Image4, &ui_img_sunny_png);
    lv_obj_set_width(ui_Image4, 129);
    lv_obj_set_height(ui_Image4, 121);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 150);

    ui_WTime3 = lv_label_create(ui_HourWeather2);
    lv_obj_set_width(ui_WTime3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTime3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTime3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WTime3, "1500");
    lv_obj_set_style_text_color(ui_WTime3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTime3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTime3, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WTemp3 = lv_label_create(ui_HourWeather2);
    lv_obj_set_width(ui_WTemp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTemp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTemp3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WTemp3, "48");
    lv_obj_set_style_text_color(ui_WTemp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTemp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTemp3, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourWeather3 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_HourWeather3, 75);
    lv_obj_set_height(ui_HourWeather3, 175);
    lv_obj_set_x(ui_HourWeather3, -41);
    lv_obj_set_y(ui_HourWeather3, 72);
    lv_obj_set_align(ui_HourWeather3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HourWeather3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourWeather3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourWeather3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_HourWeather3);
    lv_img_set_src(ui_Image5, &ui_img_sunny_png);
    lv_obj_set_width(ui_Image5, 129);
    lv_obj_set_height(ui_Image5, 121);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 150);

    ui_WTime4 = lv_label_create(ui_HourWeather3);
    lv_obj_set_width(ui_WTime4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTime4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTime4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WTime4, "1600");
    lv_obj_set_style_text_color(ui_WTime4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTime4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTime4, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WTemp4 = lv_label_create(ui_HourWeather3);
    lv_obj_set_width(ui_WTemp4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTemp4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTemp4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WTemp4, "49");
    lv_obj_set_style_text_color(ui_WTemp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTemp4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTemp4, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourWeather4 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_HourWeather4, 75);
    lv_obj_set_height(ui_HourWeather4, 175);
    lv_obj_set_x(ui_HourWeather4, -41);
    lv_obj_set_y(ui_HourWeather4, 72);
    lv_obj_set_align(ui_HourWeather4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HourWeather4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourWeather4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourWeather4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_HourWeather4);
    lv_img_set_src(ui_Image6, &ui_img_sunny_png);
    lv_obj_set_width(ui_Image6, 129);
    lv_obj_set_height(ui_Image6, 121);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 150);

    ui_WTime5 = lv_label_create(ui_HourWeather4);
    lv_obj_set_width(ui_WTime5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTime5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTime5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WTime5, "1700");
    lv_obj_set_style_text_color(ui_WTime5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTime5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTime5, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WTemp5 = lv_label_create(ui_HourWeather4);
    lv_obj_set_width(ui_WTemp5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTemp5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTemp5, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WTemp5, "49");
    lv_obj_set_style_text_color(ui_WTemp5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTemp5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTemp5, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourWeather5 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_HourWeather5, 75);
    lv_obj_set_height(ui_HourWeather5, 175);
    lv_obj_set_x(ui_HourWeather5, -41);
    lv_obj_set_y(ui_HourWeather5, 72);
    lv_obj_set_align(ui_HourWeather5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HourWeather5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourWeather5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourWeather5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_HourWeather5);
    lv_img_set_src(ui_Image7, &ui_img_sunny_png);
    lv_obj_set_width(ui_Image7, 129);
    lv_obj_set_height(ui_Image7, 121);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 150);

    ui_WTime6 = lv_label_create(ui_HourWeather5);
    lv_obj_set_width(ui_WTime6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTime6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTime6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WTime6, "1800");
    lv_obj_set_style_text_color(ui_WTime6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTime6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTime6, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WTemp6 = lv_label_create(ui_HourWeather5);
    lv_obj_set_width(ui_WTemp6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTemp6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTemp6, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WTemp6, "48");
    lv_obj_set_style_text_color(ui_WTemp6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTemp6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTemp6, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourWeather6 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_HourWeather6, 75);
    lv_obj_set_height(ui_HourWeather6, 175);
    lv_obj_set_x(ui_HourWeather6, -41);
    lv_obj_set_y(ui_HourWeather6, 72);
    lv_obj_set_align(ui_HourWeather6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HourWeather6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourWeather6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourWeather6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_HourWeather6);
    lv_img_set_src(ui_Image8, &ui_img_sunny_png);
    lv_obj_set_width(ui_Image8, 129);
    lv_obj_set_height(ui_Image8, 121);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 150);

    ui_WTime7 = lv_label_create(ui_HourWeather6);
    lv_obj_set_width(ui_WTime7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTime7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTime7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WTime7, "1900");
    lv_obj_set_style_text_color(ui_WTime7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTime7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTime7, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WTemp7 = lv_label_create(ui_HourWeather6);
    lv_obj_set_width(ui_WTemp7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTemp7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTemp7, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WTemp7, "45");
    lv_obj_set_style_text_color(ui_WTemp7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTemp7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTemp7, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourWeather7 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_HourWeather7, 75);
    lv_obj_set_height(ui_HourWeather7, 175);
    lv_obj_set_x(ui_HourWeather7, -41);
    lv_obj_set_y(ui_HourWeather7, 72);
    lv_obj_set_align(ui_HourWeather7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HourWeather7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourWeather7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourWeather7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_HourWeather7);
    lv_img_set_src(ui_Image9, &ui_img_evening_png);
    lv_obj_set_width(ui_Image9, 94);
    lv_obj_set_height(ui_Image9, 101);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 150);

    ui_WTime8 = lv_label_create(ui_HourWeather7);
    lv_obj_set_width(ui_WTime8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTime8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTime8, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WTime8, "2000");
    lv_obj_set_style_text_color(ui_WTime8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTime8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTime8, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WTemp8 = lv_label_create(ui_HourWeather7);
    lv_obj_set_width(ui_WTemp8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTemp8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTemp8, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WTemp8, "41");
    lv_obj_set_style_text_color(ui_WTemp8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTemp8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTemp8, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourWeather8 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_HourWeather8, 75);
    lv_obj_set_height(ui_HourWeather8, 175);
    lv_obj_set_x(ui_HourWeather8, -41);
    lv_obj_set_y(ui_HourWeather8, 72);
    lv_obj_set_align(ui_HourWeather8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HourWeather8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourWeather8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourWeather8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_HourWeather8);
    lv_img_set_src(ui_Image10, &ui_img_evening_png);
    lv_obj_set_width(ui_Image10, 94);
    lv_obj_set_height(ui_Image10, 101);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 150);

    ui_WTime9 = lv_label_create(ui_HourWeather8);
    lv_obj_set_width(ui_WTime9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTime9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTime9, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WTime9, "2100");
    lv_obj_set_style_text_color(ui_WTime9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTime9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTime9, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WTemp9 = lv_label_create(ui_HourWeather8);
    lv_obj_set_width(ui_WTemp9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTemp9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTemp9, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WTemp9, "39");
    lv_obj_set_style_text_color(ui_WTemp9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTemp9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTemp9, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourWeather9 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_HourWeather9, 75);
    lv_obj_set_height(ui_HourWeather9, 175);
    lv_obj_set_x(ui_HourWeather9, -41);
    lv_obj_set_y(ui_HourWeather9, 72);
    lv_obj_set_align(ui_HourWeather9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HourWeather9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HourWeather9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourWeather9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_HourWeather9);
    lv_img_set_src(ui_Image11, &ui_img_evening_png);
    lv_obj_set_width(ui_Image11, 94);
    lv_obj_set_height(ui_Image11, 101);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image11, 150);

    ui_WTime10 = lv_label_create(ui_HourWeather9);
    lv_obj_set_width(ui_WTime10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTime10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTime10, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WTime10, "2200");
    lv_obj_set_style_text_color(ui_WTime10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTime10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTime10, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WTemp10 = lv_label_create(ui_HourWeather9);
    lv_obj_set_width(ui_WTemp10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WTemp10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WTemp10, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_WTemp10, "37");
    lv_obj_set_style_text_color(ui_WTemp10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WTemp10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WTemp10, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Environment);
    lv_obj_set_width(ui_Panel6, 480);
    lv_obj_set_height(ui_Panel6, 115);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 100);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel6, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel4, 480);
    lv_obj_set_height(ui_Panel4, 25);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AQIBar = lv_bar_create(ui_Panel4);
    lv_bar_set_value(ui_AQIBar, 34, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_AQIBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_AQIBar, 150);
    lv_obj_set_height(ui_AQIBar, 17);
    lv_obj_set_align(ui_AQIBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AQIBar, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AQIBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AQIBar, lv_color_hex(0x14FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AQIBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AQIBar, lv_color_hex(0x00FF33), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AQIBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AQIBar, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AQIBar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_AQIVal = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_AQIVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AQIVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AQIVal, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_AQIVal, "34");
    lv_obj_set_style_text_color(ui_AQIVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AQIVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AQIVal, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label7, "AQI");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel1, 480);
    lv_obj_set_height(ui_Panel1, 25);
    lv_obj_set_x(ui_Panel1, -6);
    lv_obj_set_y(ui_Panel1, 14);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempBar = lv_bar_create(ui_Panel1);
    lv_bar_set_value(ui_TempBar, 44, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TempBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TempBar, 150);
    lv_obj_set_height(ui_TempBar, 17);
    lv_obj_set_align(ui_TempBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_TempBar, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TempBar, lv_color_hex(0xFFAA00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TempBar, lv_color_hex(0xFFC200), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TempBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TempBar, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TempBar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_TEMP = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_TEMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TEMP, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TEMP, "44 F");
    lv_obj_set_style_text_color(ui_TEMP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TEMP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TEMP, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label2, "TEMP");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel3, 480);
    lv_obj_set_height(ui_Panel3, 25);
    lv_obj_set_x(ui_Panel3, -6);
    lv_obj_set_y(ui_Panel3, 14);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidBar = lv_bar_create(ui_Panel3);
    lv_bar_set_value(ui_HumidBar, 45, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_HumidBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HumidBar, 150);
    lv_obj_set_height(ui_HumidBar, 17);
    lv_obj_set_align(ui_HumidBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_HumidBar, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumidBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HumidBar, lv_color_hex(0x00F1FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumidBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HumidBar, lv_color_hex(0x00F8FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HumidBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HumidBar, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HumidBar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Humid = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Humid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Humid, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Humid, "45%");
    lv_obj_set_style_text_color(ui_Humid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humid, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label9, "HUMIDITY");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel5, 480);
    lv_obj_set_height(ui_Panel5, 25);
    lv_obj_set_x(ui_Panel5, -6);
    lv_obj_set_y(ui_Panel5, 14);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_COBar = lv_bar_create(ui_Panel5);
    lv_bar_set_range(ui_COBar, 0, 5000);
    lv_bar_set_value(ui_COBar, 1664, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_COBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_COBar, 150);
    lv_obj_set_height(ui_COBar, 17);
    lv_obj_set_align(ui_COBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_COBar, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_COBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_COBar, lv_color_hex(0x005FFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_COBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_COBar, lv_color_hex(0x0029FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_COBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_COBar, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_COBar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_CO2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_CO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CO2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_CO2, "1664");
    lv_obj_set_style_text_color(ui_CO2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label12, "CO2");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_AQIBar, ui_event_AQIBar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempBar, ui_event_TempBar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HumidBar, ui_event_HumidBar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_COBar, ui_event_COBar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Environment, ui_event_Environment, LV_EVENT_ALL, NULL);

}
