// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Test1

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 480);
    lv_obj_set_height(ui_Container2, 320);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -2);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hour = ui_Hour_create(ui_Container2);
    lv_obj_set_x(ui_Hour, -100);
    lv_obj_set_y(ui_Hour, 0);

    ui_Colon = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Colon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Colon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Colon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Colon, ":");
    lv_obj_set_style_text_color(ui_Colon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Colon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Colon, &ui_font_Large, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minute = ui_Minute_create(ui_Container2);
    lv_obj_set_x(ui_Minute, 100);
    lv_obj_set_y(ui_Minute, 0);

    lv_obj_add_event_cb(ui_Main, ui_event_Main, LV_EVENT_ALL, NULL);

}
