// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Test1

#ifndef _UI_COMP_HOUR_H
#define _UI_COMP_HOUR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Hour
#define UI_COMP_HOUR_HOUR 0
#define _UI_COMP_HOUR_NUM 1
lv_obj_t * ui_Hour_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
