// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Test1

#include "../ui.h"


// COMPONENT Minute

lv_obj_t * ui_Minute_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Minute;
    cui_Minute = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Minute, 75);
    lv_obj_set_y(cui_Minute, 0);
    lv_obj_set_align(cui_Minute, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Minute, "00");
    lv_obj_set_style_text_color(cui_Minute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Minute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Minute, &ui_font_Large, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MINUTE_NUM);
    children[UI_COMP_MINUTE_MINUTE] = cui_Minute;
    lv_obj_add_event_cb(cui_Minute, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Minute, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Minute_create_hook(cui_Minute);
    return cui_Minute;
}

