// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Test1

#include "../ui.h"


// COMPONENT Hour

lv_obj_t * ui_Hour_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Hour;
    cui_Hour = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Hour, -70);
    lv_obj_set_y(cui_Hour, 0);
    lv_obj_set_align(cui_Hour, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Hour, "12");
    lv_obj_set_style_text_color(cui_Hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(cui_Hour, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(cui_Hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Hour, &ui_font_Large, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HOUR_NUM);
    children[UI_COMP_HOUR_HOUR] = cui_Hour;
    lv_obj_add_event_cb(cui_Hour, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Hour, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Hour_create_hook(cui_Hour);
    return cui_Hour;
}

