// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Test1

#include "../ui.h"

void ui_comp_TIME_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Hour_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Minute_create_hook(lv_obj_t * comp)
{
}

void ui_comp_HourWeather_create_hook(lv_obj_t * comp)
{
}
