// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Test1

#ifndef _UI_COMP_HOURWEATHER_H
#define _UI_COMP_HOURWEATHER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT HourWeather
#define UI_COMP_HOURWEATHER_HOURWEATHER 0
#define UI_COMP_HOURWEATHER_IMAGE1 1
#define UI_COMP_HOURWEATHER_WTIME 2
#define UI_COMP_HOURWEATHER_WTEMP 3
#define _UI_COMP_HOURWEATHER_NUM 4
lv_obj_t * ui_HourWeather_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
