// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Test1

#ifndef _TEST1_UI_COMP_HOOK_H
#define _TEST1_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Hour_create_hook(lv_obj_t * comp);
void ui_comp_HourWeather_create_hook(lv_obj_t * comp);
void ui_comp_Minute_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
